name: Screenshot with Puppeteer

on: [push, workflow_dispatch]

jobs:
  screenshot:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Run Puppeteer
        run: node screenshot.js
